// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3VPE4-3wEV93cC__x9GPipSNCCYEYccA',
    appId: '1:755103054617:web:d89ee93d1133946434e388',
    messagingSenderId: '755103054617',
    projectId: 'sistema-citas-b1096',
    authDomain: 'sistema-citas-b1096.firebaseapp.com',
    storageBucket: 'sistema-citas-b1096.appspot.com',
    measurementId: 'G-G0KPXS5KLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmV1tYEiaMMRD6efXc2gzOjiFfs8GXBSY',
    appId: '1:755103054617:android:480af7dae43b78fd34e388',
    messagingSenderId: '755103054617',
    projectId: 'sistema-citas-b1096',
    storageBucket: 'sistema-citas-b1096.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSc_-auKgX1gWoaMaCS1z5QuyvQEIcFbY',
    appId: '1:755103054617:ios:87085f885641416e34e388',
    messagingSenderId: '755103054617',
    projectId: 'sistema-citas-b1096',
    storageBucket: 'sistema-citas-b1096.appspot.com',
    iosBundleId: 'com.example.sistemaCitas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSc_-auKgX1gWoaMaCS1z5QuyvQEIcFbY',
    appId: '1:755103054617:ios:c9560dbd829a273034e388',
    messagingSenderId: '755103054617',
    projectId: 'sistema-citas-b1096',
    storageBucket: 'sistema-citas-b1096.appspot.com',
    iosBundleId: 'com.example.sistemaCitas.RunnerTests',
  );
}
