const LOGIN_SCREEN = 'LOGIN_SCREEN';
const SIGN_IN_SCREEN = 'SIGN_IN_SCREEN';
const MEDICAL_APPOINTMENTS_SCREEN = 'MEDICAL_APPOINTMENTS_SCREEN';
const PENDING_APPOINTMENTS_SCREEN = 'PENDING_APPOINTMENTS_SCREEN';
const CHAT_SCREEN = 'CHAT_SCREEN';
